#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and to other things
count=1
while [ $count -le 20 ]; do
	echo "$count"
	case "$count" in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((count++))
done
