#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:
hour=0
second=1
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	while [ $second -le 59 ]; do
		echo $second
		((second++))
	done
	second=1
	((hour++))
done
